version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: iskra_ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # use 'all' if you want to allocate all GPUs
              capabilities: [gpu]
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:stable # Use the stable HA version
    container_name: iskra_homeassistant
    ports:
      - "127.0.0.1:8123:8123" # Port for the HA web interface
    volumes:
      - ./homeassistant_config:/config # Mount configuration directory for HA
      - /etc/localtime:/etc/localtime:ro # Sync time with host (important for automations)
    privileged: true # May be required for some devices; try without first
                     # or forward specific devices if known. Start like this for now.
    restart: unless-stopped

volumes:
  ollama_data:
  homeassistant_config: # Docker will create this named volume if ./homeassistant_config is absent
                        # For predictability, like with ollama_data, create ./homeassistant_config manually
