version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: iskra_ollama
    ports:
      - "192.168.86.24:11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped
    # Добавляем переменные окружения здесь
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: iskra_homeassistant
    ports:
      - "192.168.86.24:8123:8123"
    volumes:
      - ./homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
