# Telegram Bot Configuration
telegram_bot:
  token: "8119528334:AAF8IsQTtlvexdXWq8kSr8yANDSpcUgLISU"  # Замени на реальный токен твоего "Обсидиана"

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434" # URL, по которому доступен API Ollama (запущенного в Docker)
  default_model: "yandex/YandexGPT-5-Lite-8B-instruct-GGUF:latest" # Наша выбранная модель

# Home Assistant Configuration
home_assistant:
  base_url: "http://localhost:8123" # URL, по которому доступен API Home Assistant
  long_lived_access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlZjQ2YWNiYzNhYjA0N2ZlOTlhOWQ5NDg0MGEzNzZjMiIsImlhdCI6MTc0ODIwMTI0NCwiZXhwIjoyMDYzNTYxMjQ0fQ.OWepQnN8aVu5Kxij3Iq3_iuZoidjwrPNaOe4t81Jd4g" # Замени на твой долгосрочный токен HA

# Возможно, какие-то другие настройки, которые нам понадобятся в будущем:
# Например, настройки для конкретных устройств, если мы не будем все делать через HA
# Или настройки для пользователя (твои предпочтения)
# Пока оставим так, потом дополним по мере необходимости.

# Logging Configuration (пример, потом можем настроить детальнее)
logging:
  level: "INFO" # Возможные уровни: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "familiar_app.log" # Куда писать логи (относительно корня проекта или абсолютный путь)
